contrib: add memory statistics to ps.py
osandov/drgn pull request #257
Opened 2023-01-30 14:31 UTC by marxin

New output of the command is:

```
PID     PPID    CPU  ST   VMS    RSS  MEM%  COMM
1       0       15   S   165M    15M   0.1 systemd
2       0       5    S      0      0   0.0 [kthreadd]
3       2       0    I      0      0   0.0 [rcu_gp]
4       2       0    I      0      0   0.0 [rcu_par_gp]
5       2       0    I      0      0   0.0 [slub_flushwq]
6       2       0    I      0      0   0.0 [netns]
8       2       0    I      0      0   0.0 [kworker/0:0H]
10      2       0    I      0      0   0.0 [mm_percpu_wq]
11      2       0    I      0      0   0.0 [rcu_tasks_kthre]
12      2       0    I      0      0   0.0 [rcu_tasks_rude_]
...
1933    1294    14   S  1904M   368M   2.8 drgn
1934    1294    15   S  1904M   368M   2.8 drgn
1935    1294    0    S  1904M   368M   2.8 drgn
1936    1294    1    S  1904M   368M   2.8 drgn
1937    1294    2    S  1904M   368M   2.8 drgn
1938    1294    3    S  1904M   368M   2.8 drgn
1939    1294    4    S  1904M   368M   2.8 drgn
...
```

Signed-off-by: Martin Liska <mliska@suse.cz>

2023-01-30 14:33 UTC, marxin commented
A few questions here:

- What about adding `get_task_memory_info` to helpers? It can mimic `cat /proc/$pid/statm` ?
- Similarly for `format_bytes` ?
- Can one somehow locally run qemu tests using the images you periodically build? I would like to test `v6.2-rcX` release here.

2023-01-31 20:37 UTC, marxin commented
> * Similarly for `format_bytes` ?

Note this can be used here as well:
https://github.com/osandov/drgn/blob/55e098b5606a8a2e87ab9bc6e231455ed0c29cf0/contrib/lsmod.py#L25

2023-02-01 21:25 UTC, osandov commented
> A few questions here:
> 
> * What about adding `get_task_memory_info` to helpers? It can mimic `cat /proc/$pid/statm` ?
> * Similarly for `format_bytes` ?

I just pushed https://github.com/osandov/drgn/commit/b51f5a3c31b2b8039386953e568d663d6356b1cb adding `drgn.helpers.common.format.number_in_binary_units()`. Thanks for the suggestion!

> * Can one somehow locally run qemu tests using the images you periodically build? I would like to test `v6.2-rcX` release here.

Yes, you can run the `vmtest.vm` module. Try `python3 -m vmtest.vm --help`. For example, run the current build of drgn in Linux 6.2, do `python3 -m vmtest.vm -k '6.2.*' python3 -Bm drgn`.

I haven't looked at the rest yet.

2023-02-02 21:47 UTC, marxin commented
> I just pushed [b51f5a3](https://github.com/osandov/drgn/commit/b51f5a3c31b2b8039386953e568d663d6356b1cb) adding `drgn.helpers.common.format.number_in_binary_units()`. Thanks for the suggestion!

Very nice and works smoothly for me, I've used the function in this pull request.

2023-02-02 21:47 UTC, marxin commented
> Yes, you can run the `vmtest.vm` module. Try `python3 -m vmtest.vm --help`. For example, run the current build of drgn in Linux 6.2, do `python3 -m vmtest.vm -k '6.2.*' python3 -Bm drgn`.

Great, that's a very nice tooling you built for testing purposes.

2023-02-03 09:37 UTC, marxin commented
One more question: can one somehow run: `python3 -m vmtest.vm -k all` which would run the script for all known kernel images? Would be handly for the contrib scripts testing.

2023-02-09 16:25 UTC, marxin commented
> One more question: can one somehow run: `python3 -m vmtest.vm -k all` which would run the script for all known kernel images? Would be handly for the contrib scripts testing.

I partially addressed that in #272, let's discuss it there.

2023-02-24 20:29 UTC, osandov requested changes
One trivial comment, otherwise this looks good to go.

2023-02-24 20:29 UTC, osandov commented on contrib/ps.py
> +totalram = (PAGE_SIZE * ram_pages).value_()
You can use your new `totalram_pages()` helper here now.

2023-02-25 10:07 UTC, merged