Handle zero pc in x86_64 fallback unwind
osandov/drgn pull request #343
Opened 2023-08-09 02:07 UTC by inwardvessel

Sometimes a stack trace cannot be unwound because of pc being zero and we end up with a single empty frame: `0: 0x0`. In these cases, we can assume a NULL function pointer was called and then modify RIP and RSP so that they are associated with the frame of the "caller of the NULL function pointer". This allows the stack to be unwound, revealing every frame below the NULL call. A new function is added to perform this manipulation of registers, and is then used within the x86_64 fallback unwinder where attempting to get registers from the frame pointer fails and pc is found to be zero.

2023-08-15 21:52 UTC, osandov requested changes
Thanks for the fix! A few minor comments. Could you please also split the new `drgn_register_dup()` function into its own commit?

2023-08-15 21:52 UTC, osandov commented on libdrgn/register_state.c
> +	size_t size = 0;
No need to initialize this, it's overwritten in a couple of lines.
```suggestion
	size_t size;
```

2023-08-15 21:52 UTC, osandov commented on libdrgn/register_state.c
> +	memcpy(ret->buf, regs->buf, regs->regs_size);
This can be a single `memcpy`:

```suggestion
	memcpy(ret, regs, size);
```

2023-08-15 21:52 UTC, osandov commented on libdrgn/arch_x86_64.c
> +			if (pc.has_value && pc.value == 0)
I think it'd be better to check this NULL call case before trying to use the frame pointer. (If frame pointers are enabled, then after a call of NULL, the frame pointer will still point to the caller of the function that called NULL, and thus we'll skip the function that called NULL, which is the one we care about.)

2023-08-15 21:52 UTC, osandov commented on libdrgn/arch_x86_64.c
> +		sizeof(postcall_rip), false);
This won't properly byte swap if you're debugging a x86-64 core dump from a big-endian host. Instead:

```suggestion
	err = drgn_program_read_u64(prog, rsp.value, false, &postcall_rip);
```

2023-08-15 21:52 UTC, osandov commented on libdrgn/arch_x86_64.c
> +	struct drgn_register_state *tmp = drgn_register_state_dup(regs);
Need to check that the allocation succeeded.

```suggestion
	struct drgn_register_state *tmp = drgn_register_state_dup(regs);
	if (!tmp)
		return &drgn_enomem;
```

2023-08-15 23:12 UTC, inwardvessel commented
made all requested changes.

2023-08-18 22:38 UTC, osandov requested changes
A few more small style things, but this looks good functionally. Could you please also add a bit more explanation to the commit messages? It'd be nice to have some background about how you found this issue and what it fixes for you.

2023-08-18 22:38 UTC, osandov commented on libdrgn/register_state.c
> +		const struct drgn_register_state *regs)
Style nit: let's format it like this:

```suggestion
struct drgn_register_state *
drgn_register_state_dup(const struct drgn_register_state *regs)
```

2023-08-18 22:38 UTC, osandov commented on libdrgn/register_state.h
> +		const struct drgn_register_state *regs);
Same style nit as above, and let's document this:

```suggestion
/**
 * Create a copy of a @ref drgn_register_state.
 *
 * @return New register state on success, @c NULL on failure to allocate memory.
 */
struct drgn_register_state *
drgn_register_state_dup(const struct drgn_register_state *regs);
```

2023-08-18 22:38 UTC, osandov commented on libdrgn/arch_x86_64.c
> +	pc = drgn_register_state_get_pc(regs);
Style nit, and let's expand on the comment a little bit:

```suggestion
	/*
	 * If the program counter is 0, it's likely that a NULL function pointer
	 * was called. Assume that the only thing we need to unwind is a single
	 * call instruction.
	 */
	struct optional_uint64 pc = drgn_register_state_get_pc(regs);
```

2023-08-18 22:38 UTC, osandov commented on libdrgn/arch_x86_64.c
> +		       struct drgn_register_state **ret)
Style:
```suggestion
static struct drgn_error *unwind_call(struct drgn_program *prog,
				      struct drgn_register_state *regs,
				      struct drgn_register_state **ret)
```

2023-08-22 22:50 UTC, inwardvessel commented
requested changes made and expanded commit messages.

2023-08-24 23:05 UTC, merged

2023-08-24 23:05 UTC, osandov commented
I made some small style/comment tweaks, so this is good to go. Thanks, this is a great addition! I wonder if we'll want something similar for other architectures.