Add linux kernel module helpers
osandov/drgn pull request #411
Opened 2024-07-03 03:16 UTC by brenns10

There are a few common use cases that I find myself re-writing: iterating over the list of modules, looking up a module by name, and getting memory addresses related to modules (or vice versa). Add helpers for each.

---

I know there is the _drgn_ module API which is upcoming, and I don't necessarily want to confuse or overlap with that. So maybe it's possible this will duplicate that API in some form, but I find myself needing to access kernel modules or look them up by name/address rather frequently. So here's some code and tests (tested on 6.9 and 4.19, hoping to let CI take a look at the rest :wink: ).

2024-07-03 03:18 UTC, brenns10 commented
So, I'm not sure how the module API issue 332 got linked to this pull request... I did not mention it by number? I mentioned the title though. Is that enough to accidentally link issues and pull requests? If so... booo.

2024-07-11 21:54 UTC, osandov requested changes
Thanks, I agree that this still makes sense even with the module API. Some minor comments. (I unlinked the issue, maybe it was because your branch had the same name as the branch I had previously linked to it? That's weird.)

2024-07-11 21:54 UTC, osandov commented on drgn/helpers/linux/module.py
> +def lookup_module(prog: Program, name: Union[str, bytes]) -> Object:
The equivalent kernel function is named [`find_module()`](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/linux/module.h?h=v6.10-rc7#n657), so let's use that name.

2024-07-11 21:54 UTC, osandov commented on drgn/helpers/linux/module.py
> +def address_to_module(prog: Program, addr: IntegerLike) -> Object:
The equivalent kernel function is [`__module_address()`](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/linux/module.h?h=v6.10-rc7#n614), but that name doesn't make much sense to me, so this is fine.

2024-07-11 21:54 UTC, osandov commented on drgn/helpers/linux/module.py
> +        idx = int(mod_tree.root.seq.sequence & 1)
I have a slight preference for:
```suggestion
        idx = mod_tree.root.seq.seqcount.sequence.value_() & 1
    except AttributeError:
        idx = mod_tree.root.seq.sequence.value_() & 1
```

2024-07-11 21:58 UTC, osandov commented
One more thing, the test case is failing for me with !SMP:

```
$ python3 setup.py test -k '*tiny'
...
======================================================================
FAIL: test_module_percpu_region (tests.linux_kernel.helpers.test_module.TestModules.test_module_percpu_region)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/osandov/repos/drgn3/tests/linux_kernel/helpers/test_module.py", line 32, in test_module_percpu_region
    self.assertTrue(start <= pcpu_addr <= start + size)
AssertionError: False is not true
```

2024-07-11 23:36 UTC, brenns10 commented
Huh, I guess I was getting too clever about that test. On !SMP the start should be 0, i.e. NULL, so I will probably only conditionally assert if `start != 0`. Since it's still a nice test of functionality for SMP kernels.

2024-07-13 03:01 UTC, osandov approved these changes

2024-07-13 03:01 UTC, merged